version: '3.7'
services:
  database:
    restart: always
    image: postgres:12
    container_name: herdbook-db
    environment:
      - POSTGRES_DB=herdbook
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-insecure}
      - POSTGRES_USER=herdbook
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  optisel:
    container_name: optisel 
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
        - OPTISEL_PORT=31113
        - OPTISEL_BIND_ADDR=0.0.0.0
        - POSTGRES_HOST=herdbook-db
    volumes:
      - ./R:/usr/local/optisel/R
    image: optisel 
    ports:
        - 31113:31113 

